describe('todo project', () => {
    it('should visit the home page', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[data-test-id="home-page-main"]')
        cy.get('[data-test-id="home-page-title"]')
            .should('have.text', 'Today')
    })
    it('should visit the add todo page', () => {
        cy.visit('http://localhost:3000/')
        cy.get('[data-test-id="add-todo-page"]')
            .click()
        cy.get('[data-test-id="add-todo-title"]')
            .should("have.text", 'Add todo item')
    })
    it('should add new todo', () => {
        cy.get('[data-test-id="form-description"]')
            .type('New task here')
        cy.get('[data-test-id="form-group"]')
            .select('personal')
        cy.get('[data-test-id="form-category"]')
            .check('quick-task')
        cy.get('[data-test-id="form-estimated-time"]')
            .type('2 mins')
        cy.get('[data-test-id="form-status"]')
            .check('not-complete')
        cy.get('button[type="submit"]')
            .click()
        cy.get('[data-test-id="all-todos"]')
            .should('have.length', 1)
    })
    it('should show detail on new todo', () => {
        cy.get('[data-test-id="new-todo-link"]')
            .click()
            .get('[data-test-id="edit-description"] h3')
            .should('have.text', 'Description: New task here')
        cy.get('[data-test-id="edit-group"] h3') 
            .should('have.text', 'Group: personal')
        cy.get('[data-test-id="edit-category"] h3') 
            .should('have.text', 'Category: quick-task')
        cy.get('[data-test-id="edit-estimated-time"] h3') 
            .should('have.text', 'Estimated Time: 2 mins')
        cy.get('[data-test-id="edit-status"] h3') 
            .should('have.text', 'Status: not-complete')
    })
    it('should let you change the description', () => {
        cy.get('[data-test-id="edit-description"] button#edit')
            .click()
            .get('[data-test-id="edit-description-field"]')
            .type('Change of task')
            .get('[data-test-id="edit-description"] button#save')
            .click() // this should update state but functionality isn't there yet
    })
})